### ISSUE TITLE
Support for arbitrary commands with argumments

### ISSUE THREAD

**Issue by rnc** [crazy-max/travis-wait-enhanced#2]
### Behaviour

Using version 0.2.0

#### Steps to reproduce this issue

1.  Run:

```
./travis-wait-enhanced --interval=1m --timeout=20m mvn compile '-Prun-its'
travis-wait-enhanced: error: unknown short flag '-P', try --help
```

#### Expected behaviour

> Tell me what should happen

Possibly after the command line argument, all remaining arguments should be consumed and passed on to the command.

#### Actual behaviour

> Tell me what happens instead

### Configuration

* travis-wait-enhanced version : 
* Platform (windows/linux) :

**Comment by crazy-max** [comment]
Hi @rnc, do you have a link to your travis build please?

**Comment by rnc** [comment]
@crazy-max Hi! Its https://travis-ci.org/release-engineering/pom-manipulation-ext/builds/587493505?utm_source=github_status&utm_medium=notification However its also quite easy to replicate on local command line with the above command.

**Comment by crazy-max** [comment]
Can you try `./travis-wait-enhanced --interval=1m --timeout=20m "mvn compile -Prun-its"` ?

**Comment by rnc** [comment]
Sorry that doesn't work either. On local command line I get
```
which mvn
/usr/local/apache-maven-3.6.0/bin/mvn
$HOME/travis-wait-enhanced --interval=1m --timeout=20m "mvn compile -Prun-its"
travis-wait-enhanced FTL Non-zero exit code for mvn compile -Prun-its error="exec: \"mvn compile -Prun-its\": executable file not found in $PATH"

$HOME/travis-wait-enhanced --interval=1m --timeout=20m mvn "compile -Prun-its"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] POM Manipulation Extension for Maven                               [pom]
....
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "compile -Prun-its". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
```

As you can see it appears to be a quoting problem. Quoting the entire thing doesn't work (as then the command isn't found) and neither does quoting the parameters (as the child process doesn't split up the parameters). 


**Woah** .... just tried 
```
$HOME/travis-wait-enhanced --interval=1m --timeout=20m -- mvn -V clean install -Prun-its 
```

And that seems to work .... I guess the `--` is an option in the Go library you are using for parsing. I'll try it on the CI now and if it works I can send a PR to document this if you want.

**Comment by crazy-max** [comment]
Yeah thanks feel free to open a PR 🎉

**Comment by rnc** [comment]
CI works with the `--` : https://travis-ci.org/release-engineering/pom-manipulation-ext/builds/587521482
