### ISSUE TITLE
Configurable keep-alive message

### ISSUE THREAD

**Issue by zajozorPho** [crazy-max/travis-wait-enhanced#5]
We are using `travis-wait-enhanced` along with python's `pytest` suite.
Some of our tests take so long, that they would time out without the keep-alive message.

This tool comes in handy, but the keep-alive messages kind of break the `pytest` output like this:

```
tests/test_xxx.py .                                  [  5%]
tests/test_yyy.py travis-wait-enhanced INF Still running at Wed, 16 Oct 2019 17:07:05 UTC...
.....                       [ 17%]
tests/test_zzz.py .FFF                                               [ 19%]
tests/test_aaa.py travis-wait-enhanced INF Still running at Wed, 16 Oct 2019 17:17:00 UTC...
travis-wait-enhanced INF Still running at Wed, 16 Oct 2019 17:26:55 UTC...
......F...                   [ 31%]
tests/bbb.py .....                                                 [ 33%]
tests/ccc.py ..EFE.      
```

For this case I would love to have a command line argument, which can change the keep-alive message, and another which removes the newline.
eg. `--keep-alive-message='*' --no-keep-alive-newline`

I can fork and try to create a PR if you are willing to merge.

**Comment by crazy-max** [comment]
Hi @zajozorPho!

Thanks for your suggestion, feel free to open a PR!
